src/App.js, src/components/Form.jsx
=> [Grupo 18] Felipe, JP, João Vitor, Olávio, Victor

cypress/integration/header_spec.js, src/App.js, src/Pages/Perfil.jsx, src/components/Header.js
11 - Redirecione a pessoa usuária para a tela de perfil ao clicar no botão de perfil
- A mudança de tela ocorre corretamente
=> [GRUPO 3] REQUISITO 11

cypress/integration/header_spec.js, src/App.js, src/Pages/ RecipesMade.jsx, src/Pages/Drinks.jsx, src/Pages/DrinksByIngredient.jsx, src/Pages/ExploreDrinks.jsx, src/Pages/ExploreFood.jsx, src/Pages/ExploreScreen.jsx, src/Pages/FavoriteRecipes.jsx, src/Pages/Food.jsx, src/Pages/FoodsByIngredient.jsx, src/Pages/FoodsByOrigin.jsx, src/Pages/Perfil.jsx, src/components/Header.js
🧾 Requisito 10🧾
Implemente um ícone para a tela de perfil, um título e um ícone para a busca, caso exista no protótipo
Todas as rotas serão verificadas. Os ícones podem ser encontrados em src/images/profileIcon.svg e em src/images/searchIcon.svg.
📸 Print 📸
=> [GRUPO 3] REQUISITO 10

src/pages/LoginPage.jsx
**Observações técnicas**
-   O token de teste é sempre  `1`.
```
- Após a submissão mealsToken e cocktailsToken devem estar salvos em localStorage
```
**Observações técnicas**
-   Após a submissão, o e-mail de pessoa usuária deve ser salvo em  `localStorage`  na chave  `user`  no formato  `{ email: email-da-pessoa }`.
```
- Após a submissão a chave user deve estar salva em localStorage
```
```
- A rota muda para a tela principal de receitas de comidas
```
=> [GRUPO 12] Requisitos 6, 7 e 8 - FINALIZADOS

cypress/integration/header_search_bar_spec.js, src/Pages/Food.jsx, src/components/SearchBar.js
Implemente os elementos da barra de busca respeitando os atributos descritos no protótipo
Deve existir os data-testids tanto da barra de busca quanto de todos os radio-buttons.
Observações técnicas
O radio button de busca de ingrediente deve possuir o atributo data-testid="ingredient-search-radio";
O radio button de busca por nome deve possuir o atributo data-testid="name-search-radio";
O radio button de busca da primeira letra deve possuir o atributo data-testid="first-letter-search-radio".
O botão de busca deve possuir o atributo data-testid="exec-search-btn"
- Tem os data-testids tanto da barra de busca quanto de todos os radio-buttons
=> [GRUPO 3] Requisito 13

src/App.js, src/helpers/renderWithReduxAndRouter.js, src/pages/FoodRecipes.jsx, src/pages/Login.jsx, src/tests/App.test.js, src/tests/Login.test.js
P.S. Não implementamos os testes dos requisitos 7 e 8; Motivo: teste de localStorage.
=> [GRUPO 26] - Requisitos 1 ao 8 (Tela de Login)

cypress/integration/header_search_bar_spec.js, src/components/SearchBar.js, src/context/Context.js
Posicione a barra logo abaixo do header e implemente 3 radio buttons: Ingrediente, Nome e Primeira letra
A barra de busca deve ficar logo abaixo do header e deve possuir 3 radio buttons: Ingrediente, Nome e Primeira letra. Eles, em conjunto com a search-input, devem mudar a forma como serão filtradas as receitas após clicar no botão Buscar. Os endpoints da API que você deve usar podem ser consultados aqui para a API de comidas e aqui para a API de bebidas.
Observações técnicas
Se o radio selecionado for Ingrediente, a busca na API é feita corretamente pelo ingrediente. O endpoint utilizado deve ser https://www.themealdb.com/api/json/v1/1/filter.php?i={ingrediente};
Se o radio selecionado for Nome, a busca na API é feita corretamente pelo nome. O endpoint utilizado deve ser …
=> [GRUPO 3] Requisito 14

src/components/ComponentLogin.js, src/pages/Perfil.js, yarn.lock
Reverts tryber/sd-013-a-project-recipes-app#190
=> Revert "Group 4 tela de perfil"

src/App.js, src/context/provider.js, src/pages/recipeDetail/index.js
Cria tela de detalhes de COMIDA , sem o video e sem recomendacoes
=> [TELA DE DETALHES]

src/App.js, src/pages/recipeDetail/drinksDetails.js, src/pages/recipeDetail/mealDetails.js
Adiciona a tela de detalhes para as bebidas, sem o video e sem as recomendacoes
=> [TELA DE DETALHES BEBIDAS]

cypress/integration/header_search_bar_spec.js, src/context/Provider.js, src/pages/Bebidas.js, src/pages/Comidas.js
… testes. As chamadas da primeira API de comidas/bebidas, estao sendo feitas no Provider agora.
=> [Grupo 19] Correcao de bugs de requisitos que foram feitos e nao estavam passando mais no teste.

src/components/recomendationCard.js, src/contexts/appProvider.js, src/pages/FoodDetails.js, src/pages/css/foodDetails.css
não está completo, e não passa em boa parte dos testes, pois está faltando a segunda tela (bebidas) que será implementada quando todas as funções estiverem implementadas (e alguns data-testIds!).
=> [INCOMPLETO] tela de detalhes

src/tests/RecipeDetails.test.js
=> [Grupo 24] Corrigido lint dos testes

cypress/integration/header_search_bar_spec.js, src/Pages/Drinks.jsx, src/Pages/Food.jsx, src/components/SearchBar.js
Exiba um alert caso nenhuma receita seja encontrada
O alert deve contendo o texto "Sinto muito, não encontramos nenhuma receita para esses filtros."
- Caso nenhuma comida seja encontrada o alert deve ser exibido
- Caso nenhuma bebida seja encontrada o alert deve ser exibido
=> [GRUPO 3] Requisito 18

src/pages/ExplorePage.jsx
```
- Tem os data-testids explore-food e explore-drinks.
```
Verifica se o atributo  `data-testid="explore-food"`  possui o texto "Explorar Comidas" e se o  `data-testid="explore-drinks"`  possui o texto "Explorar Bebidas".
```
- O nomes dos botões devem ser "Explorar Comidas" e "Explorar Bebidas"
```
```
- Ao clicar no botão "Explorar Comidas" a rota muda para a página de explorar comidas;
- Ao clicar no botão "Explorar Bebidas" a rota muda para a página de explorar bebidas.
```
=> [GRUPO 12] TELA DE EXPLORAR - Requisitos 67-69 - OK

src/Pages/Perfil.jsx
82 - Implemente os elementos da a tela de perfil respeitando os atributos descritos no protótipo
Observações técnicas
Todos o data-testid do email e de todos os botões
O elemento de email deve possuir o atributo data-testid="profile-email";
O botão com as "Receitas Feitas" deve possuir o atributo data-testid="profile-done-btn";
O botão com as "Receitas Favoritas" deve possuir o atributo data-testid="profile-favorite-btn";
O botão de sair deve possuir o atributo data-testid="profile-logout-btn".
- Todos o data-testid do email e de todos os botões.
84 - Implemente 3 botões: um de nome "Receitas Feitas", um de nome "Receitas Favoritas" e um de nome "Sair"
- A tela contêm todos os 3 botões.
=> [GRUPO 3] -Requisito 82 e 84

src/App.js, src/Pages/Area.jsx, src/Pages/FoodsByArea.jsx
=> [grupo 30] requisito 10

cypress/integration/favorite_recipes_spec.js, src/App.js, src/components/FavoriteCard.jsx, src/context/RecipesProvider.js, src/pages/FavoritesRecipesPage.jsx
falta resolução da localstorage
=> Group 12 develop favorites

src/tests/RecipeDetails.test.js, src/tests/RecipeInProgress.test.js, src/tests/Searchbar.test.js
Testes de receitas em progresso e ajustes nos testes da Searchbar
=> [Grupo 24] Testes de receitas em progresso

src/pages/profile.js
- componente profile funcionando perfeitamente (falta css)!
=> add profile completo!

cypress/integration/header_spec.js, src/Pages/Perfil.jsx
83 - Implemente a solução de maneira que o e-mail da pessoa usuária deve estar visível
- O e-mail armazenado em localStorage está visível.
85 - Redirecione a pessoa usuária que, ao clicar no botão de "Receitas Favoritas", a rota deve mudar para a tela de receitas favoritas
- Redireciona para a rota correta.
86 - Redirecione a pessoa usuária que, ao clicar no botão de "Receitas Feitas", a rota deve mudar para a tela de receitas feitas
- Redireciona para a rota correta.
=> [GRUPO 3] REQUISITOS 83, 85 E 86

src/components/ShareAndFavoriteButtons.jsx, src/tests/ShareAndFavoriteButtons.test.js, src/tests/TESTES.txt, src/tests/doneRecipes.test.js
Feito por Gabriel Gaspar, do grupo 22
=> [Grupo 24] Testes da página de receitas feitas

src/components/ShareAndFavoriteButtons.jsx, src/tests/ShareAndFavoriteButtons.test.js
Testes do botões de compartilhar e favoritar. Falta cobrir as linhas 35 e 36, da biblioteca de copiar.
=> [Grupo 24] Testes dos botões de compartilhar e favoritar

src/Pages/Perfil.jsx
Redirecione a pessoa usuária que, ao clicar no botão de "Sair", o localStorage deve ser limpo e a rota deve mudar para a tela de login
- Limpa todas as chaves da localStorage;
- A rota muda para a tela de login.
=> [GRUPO 3] Requisito 87

cypress/integration/header_spec.js, cypress/integration/recipes_list_spec.js, src/components/Header.jsx, src/pages/Recipes.jsx, src/redux/actions/index.js, src/services/apiRequest.js
Mudamos um pouco da lógica na page recipes. Adicionamos um useEffect que monitora a mudança do Path da página e realiza uma requisição padrão (inicial).
=> Group 26 lista de receitas

cypress/integration/header_spec.js, src/App.js, src/helpers/checkFavorite.js, src/helpers/newRecipe.js, src/helpers/renderIngredients.js, src/helpers/renderRecs.js, src/pages/Details.jsx, src/pages/Progress.jsx, src/pages/index.js, src/redux/actions/index.js, src/services/apiRequest.js, src/styles/Details.css
Requisitos 33 aos 46 + Refatoração feita + Erros de lint concertados!
=> [GRUPO 26] - Tela de Detalhes

src/App.js, src/components/favRecipes.js, src/pages/inProgress/inProgress.js, src/pages/recipeDetail/drinksDetails.js, src/pages/recipeDetail/mealDetails.js
Inicia a tela de receitas em progresso.
=> [TELA DE PROGRESSO]

src/App.js, src/pages/inProgress/inProgress.js
Reverts tryber/sd-013-a-project-recipes-app#543
=> Revert "Tentando resolver problema"

cypress/integration/recipe_in_progress_spec.js, src/App.js, src/Pages/RecipeDetail.jsx, src/Pages/RecipesInProgress.jsx, src/components/RecipeDetailCard.jsx
Desenvolva a tela de maneira que contenha uma imagem da receita, seu titulo, sua categoria (ou se a bebida é alcoólica ou não) uma lista de ingredientes com suas respectivas quantidade e suas instruções
Verifica se os atributos data-testid estão presentes na tela com suas respectivas quantidades:
A foto deve possuir o atributo data-testid="recipe-photo";
O título deve possuir o atributo data-testid="recipe-title";
O botão de compartilhar deve possuir o atributo data-testid="share-btn";
O botão de favoritar deve possuir o atributo data-testid="favorite-btn";
O texto da categoria deve possuir o atributo data-testid="recipe-category";
Os ingredientes devem possuir o atributo data-testid=${index}-ingredient-step, a verificação será feita pelo length do atributo.
O elemento de instruções deve …
=> [GRUPO 3] requisito 47

src/pages/inProgress/inProgress.js, src/pages/recipeDetail/drinksDetails.js, src/pages/recipeDetail/mealDetails.js
Resolvendo problema com localStorage
=> [RESOLVIDO]

src/components/FavoriteButton.js, src/components/ShareIcon.js, src/components/StartRecipe.js, src/contextAPI/AppProvider.js, src/pages/OriginFood.js, src/pages/Profile.js
=> [G-28] Requisito 82 - 87

cypress/integration/recipe_in_progress_spec.js, src/Pages/RecipesInProgress.jsx, src/components/RecipeDetailCard.jsx
48 - Desenvolva um checkbox para cada item da lista de ingredientes
- todos os ingredientes de uma receita de comida possuem um checkbox
- todos os ingredientes de uma receita de bebida possuem um checkbox
49 - Implemente uma lógica que, ao clicar no checkbox de um ingrediente, o nome dele deve ser "riscado" da lista
Ao clicar no checkbox, o item deve ser riscado, mostrando que esse passo foi finalizado
- verifica se é possível marcar todos os passos da receita de comida
- verifica se é possível marcar todos os passos da receita de bebida
=> [GRUPO 3] Requisito 48 e 49

src/pages/recipeDetail/drinksDetails.js, src/pages/recipeDetail/mealDetails.js
Resolve os problemas na pagina de detalhes
=> Solving details problem

src/pages/DetailsRecipePage.jsx, src/services/localStorageHandler.js
```
- Verifica botão de "Continuar Receita" na tela de detalhes de uma comida
- Verifica botão de "Continuar Receita" na tela de detalhes de uma bebida
```
=> [GRUPO 12] Requisito 40 - OK

src/components/DetailsIcons.jsx, src/pages/ProgressRecipePage.jsx, src/services/localStorageHandler.js
- Todos os requisitos passando no teste local; Super colaboração do Thomas Ravache
=> Group 12 develop rafavictor progress page
